name: Ping Streamlit Voice Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to ping the app
        run: curl https://your-username-your-repo.streamlit.app
