name: Ping Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl https://pranay-voice-bot-vrwfvr7afwcxg2pazcsszq.streamlit.app
